plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    id 'maven-publish'
    id 'signing'
}

group = 'org.dxworks.utils'
version = '1.0.0'
ext.isReleaseVersion = !version.endsWith("SNAPSHOT")

repositories {
    mavenCentral()
}

java {
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    implementation platform("org.jetbrains.kotlin:kotlin-bom:2.3.0")
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    testImplementation "org.junit.jupiter:junit-jupiter:5.7.0"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.7.0"
}

test {
    useJUnitPlatform()
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

tasks.withType(Sign).configureEach {
    onlyIf { isReleaseVersion && findProperty("signingKey") != null }
}

publishing {
    repositories {
        maven {
            name = "ossrh"
            def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username = (project.findProperty("ossrh.user") as String) ?: System.getenv("MAVEN_USERNAME")
                password = (project.findProperty("ossrh.password") as String) ?: System.getenv("MAVEN_PASSWORD")
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = 'Argumenthor'
                description = 'A library to help parse arguments from multiple, configurable sources'
                url = 'https://dxworks.github.io/argumenthor'

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer { name = 'Darius Nagy' }
                    developer { name = 'Mario Rivis' }
                }
                scm {
                    connection = 'scm:git:git://gitub.com/dxworks/argumenthor.git'
                    developerConnection = 'scm:git:ssh://gitub.com:dxworks/argumenthor.git'
                    url = 'http://gitub.com/dxworks/argumenthor'
                }
            }
        }
    }
}

signing {
    def signingKey = findProperty("signingKey")
    def signingPassword = findProperty("signingPassword")
    useInMemoryPgpKeys(signingKey, signingPassword)
    sign publishing.publications.mavenJava
}
